### ISSUE TITLE
Automating the running of this

### ISSUE THREAD

**Issue by Ropiak** [patlewis-MSFT/RemoveIntuneDevice#2]
I automated all of this except one part of your script. I'm not great with restAPI so hoping for some advice.

I'm feeding all the logins through encrypted hash files, but the part of Get-AuthToken that prompts for your Microsoft account at the beginning, I can't figure out how to feed it the password like I did with the rest of it. Any advice? If I can get it to auto submit the username/password, then this will run automatically for me

**Comment by patlewis-MSFT** [comment]
Hi @Ropiak . Intune Graph APIs do not support application authentication, so you would still need to supply a username/password.

**Comment by patlewis-MSFT** [comment]
@Ropiak : The Graph APIs now support application authentication however review the permissions here to be sure the operation that you want is supported: 

https://docs.microsoft.com/en-us/graph/permissions-reference#device-permissions
