### ISSUE TITLE
Does this actually do anything?

### ISSUE THREAD

**Issue by clickbangdead** [patlewis-MSFT/RemoveIntuneDevice#3]
Devices that have the user deleted seem to just sit there when retired, they never seem to respond to the retirement commands ( I rem'd out the delete action so I could see if they retired). So, technically you can just delete them instead of bothering to retire them, but then you can't be sure things like licensed software and the lot are removed from the devices.

**Comment by patlewis-MSFT** [comment]
Hi @clickbangdead.  At the time of the writing of the app the devices would get removed however I am trying to track down an issue now where it appears devices are still remaining in AAD even after retiring. I'll update this issue once I find out more. The problem appears to be on the service side.

**Comment by clickbangdead** [comment]
The devices just sit in retire pending state, so not sure at this point it's doing anything, which is unfortunate as this was how we implemented our termination process. Would it be helpful to open a ticket?

**Comment by patlewis-MSFT** [comment]
@clickbangdead : The current behavior is by deleting a user in AAD without deleting the user's device in Intune will cause the "orphaned" device.  The script works by querying AAD for deleted users then looping through all of the devices to match the UserID with the last user that logged in. The device object can then be used for the deleting in Intune.

When you say "the devices just sit in retire pending state", does the tool allow you to delete the device or are you saying the pending state is prior to running the script?

**Comment by patlewis-MSFT** [comment]
@clickbangdead : If the device is removed/deleted from Intune but not AAD you can also run this on the deviceID

https://docs.microsoft.com/en-us/powershell/module/msonline/remove-msoldevice?view=azureadps-1.0

**Comment by clickbangdead** [comment]
I get all that. The issue is that the device is flagged to be sent the invoke-action to retire, then the device just sits there in Intune, always in pending retirement. It'll get removed when the cleanup cycle hits as a stale device, but it doesn't seem to be actually sending the retirement packet out to the actual, physical device as far as I can tell. So, all your settings, software, whatever you put on the device would still be still there.

**Comment by clickbangdead** [comment]
Basically, I want to make sure that the retirement command is actually sending a packet to the device to retire, so that the device will actually do the retirement cycle (i.e, remove policies, revoke certs, uninstall software pacakges).

**Comment by clickbangdead** [comment]
As a side note, the orphaned devices appear to lose sync, as they don't show syncs dates after the termination of the user object.

**Comment by patlewis-MSFT** [comment]
Closing issue.
